require("hyprland.env")
require("hyprland.default")
require("hyprland.autostart")
require("hyprland.general")
require("hyprland.theme")
require("hyprland.animations")
require("hyprland.keybinds")
require("hyprland.rules")
