require("hyprland.default")

hl.on("hyprland.start", function ()
    hl.exec_cmd("kanshi")
    hl.exec_cmd("echo \"Xft.dpi:120\"|xrdb -merge")
    hl.exec_cmd("systemctl --user start hyprpolkitagent")
    hl.exec_cmd("netron -p 18081")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("fcitx5 -d")
    hl.exec_cmd("blueman-applet")
    hl.exec_cmd("nm-applet --indicator")
    hl.exec_cmd("wl-paste --watch cliphist store")
    hl.exec_cmd("waybar & swaync & safeeyes &")
    hl.exec_cmd("sleep 1.5 && hyprctl reload")
    hl.exec_cmd("firefox & syncthing & flclash & flameshot & goldendict & alacritty & hyprlock &")
    hl.exec_cmd("rdrop")
end)
